apiVersion: batch/v1
kind: Job
metadata:
  name: configure-pki
spec:
  template:
    spec:
      containers:
        - name: configure-pki
          image: vault:1.3.0
          command: ["/bin/sh"]
          args:
            - -ec
            - |
              export VAULT_ADDR="http://local-vault.default:8300"
              vault login roottoken
              vault write pki/roles/kafka-default \
                  allowed_domains=local-kafka.default \
                  allow_subdomains=true \
                  max_ttl=72h
              vault write pki/roles/cassandra-default \
                  allowed_domains=local-cassandra.default \
                  allow_subdomains=true \
                  max_ttl=72h
      restartPolicy: Never
