apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-vault
  labels:
    app: local-vault
spec:
  serviceName: local-vault
  replicas: 1
  selector:
    matchLabels:
      app: local-vault
  template:
    metadata:
      labels:
        app: local-vault
    spec:
      serviceAccountName: local-vault
      containers:
        - name: local-vault
          image: vault:1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "roottoken"
          readinessProbe:
            # Check status; unsealed vault servers return 0
            # The exit code reflects the seal status:
            #   0 - unsealed
            #   1 - error
            #   2 - sealed
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  vault status | if [ $? -ne 1 ]; then exit 0; fi
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
