apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:5.3.1
        command: [ "bash", "-c"]
        args:
        - export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${POD_NAME}.kafka.default.svc.cluster.local:9092";
          export KAFKA_BROKER_ID="$((${POD_NAME//[!0-9]/}+1))";
          /etc/confluent/docker/run;
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
          name: client
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KAFKA_LISTENER
            value: "PLAINTEXT://9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-0.zookeeper.default.svc.cluster.local:2181" # ,zookeeper-1.zookeeper.default.svc.cluster.local:2181,zookeeper-2.zookeeper.default.svc.cluster.local:2181"
          - name: KAFKA_LOG_DIR
            value: "/kafka_data/data"
          - name: KAFKA_LOG_DIRS
            value: "/kafka_data/data"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka_data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
